import argparse
import csv
import json
import re
import unicodedata
from collections import Counter
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
ROOT_DIR = BASE_DIR.parent
DEFAULT_INPUT_PATH = ROOT_DIR / "data" / "manual" / "club_mode" / "raw" / "club.txt"
ALT_INPUT_PATH = ROOT_DIR / "src" / "data" / "manual" / "club_mode" / "raw" / "club.txt"
DEFAULT_OUTPUT_PATH = ROOT_DIR / "data" / "manual" / "club_mode" / "club_players.json"
DEFAULT_SRC_OUTPUT_PATH = ROOT_DIR / "src" / "data" / "club_players.json"

SUPPORTED_LEAGUES = {
    "Premier League",
    "La Liga",
    "Serie A",
    "Bundesliga",
    "Ligue 1",
    "Champions League",
}

POSITION_ALIASES = {
    "GOALKEEPER": "GK",
    "KEEPER": "GK",
    "GK": "GK",
    "RIGHTBACK": "RB",
    "RIGHT BACK": "RB",
    "RB": "RB",
    "CENTREBACK": "CB",
    "CENTERBACK": "CB",
    "CENTRE BACK": "CB",
    "CENTER BACK": "CB",
    "CB": "CB",
    "LEFTBACK": "LB",
    "LEFT BACK": "LB",
    "LB": "LB",
    "RIGHTWINGBACK": "RWB",
    "RIGHT WING BACK": "RWB",
    "RWB": "RWB",
    "LEFTWINGBACK": "LWB",
    "LEFT WING BACK": "LWB",
    "LWB": "LWB",
    "DM": "CDM",
    "CDM": "CDM",
    "DEFENSIVE MIDFIELD": "CDM",
    "CM": "CM",
    "CENTRAL MIDFIELD": "CM",
    "AM": "CAM",
    "CAM": "CAM",
    "ATTACKING MIDFIELD": "CAM",
    "RM": "RM",
    "LM": "LM",
    "RW": "RW",
    "LW": "LW",
    "CF": "ST",
    "FW": "ST",
    "FWD": "ST",
    "STRIKER": "ST",
    "ST": "ST",
}

VALID_POSITIONS = {"GK", "RB", "CB", "LB", "RWB", "LWB", "CDM", "CM", "CAM", "RM", "LM", "RW", "LW", "ST"}
VALID_ROLE_BUCKETS = {"GK", "CB", "FB", "CDM", "CM", "CAM", "Winger", "ST"}
AUTOGENERATED_NAME_RE = re.compile(
    r"\b(?:GK|RB|CB|LB|RWB|LWB|CDM|CM|CAM|RM|LM|RW|LW|ST)\s*\d{1,2}\b",
    re.IGNORECASE,
)

OUTPUT_FIELDS = [
    "id",
    "name",
    "club",
    "league",
    "country",
    "competition",
    "position",
    "roleBucket",
    "minutes",
    "goals",
    "assists",
    "cleanSheets",
    "tacklesInterceptions",
    "keyPassesDribbles",
    "shotsOnTarget",
    "leagueMultiplier",
    "iogSeed",
    "estimated",
    "modeType",
]


def normalize_text(value: str) -> str:
    value = unicodedata.normalize("NFKD", str(value))
    return "".join(ch for ch in value if not unicodedata.combining(ch))


def slugify(value: str) -> str:
    value = normalize_text(value).lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-")


def strip_inline_comment(line: str) -> str:
    in_quote = False
    quote_char = ""
    for index, char in enumerate(line):
        if char in {"'", '"'}:
            if not in_quote:
                in_quote = True
                quote_char = char
            elif quote_char == char:
                in_quote = False
        if not in_quote and char == "#":
            return line[:index].strip()
    return line.strip()


def parse_number(value, default=0):
    if value is None:
        return default
    text = str(value).strip().replace(",", "")
    if text == "" or text.lower() in {"na", "n/a", "none", "null", "-"}:
        return default
    try:
        number = float(text)
    except ValueError:
        return default
    return int(number) if number.is_integer() else number


def parse_bool(value, default=True) -> bool:
    if value is None or str(value).strip() == "":
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "y", "estimated"}


def normalize_position(value: str) -> str:
    text = normalize_text(value or "").upper().strip()
    text = text.replace("`", "")
    text = re.sub(r"[^A-Z ]+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    compact = text.replace(" ", "")
    position = POSITION_ALIASES.get(text) or POSITION_ALIASES.get(compact) or compact
    return position if position in VALID_POSITIONS else ""


def role_from_position(position: str) -> str:
    if position == "GK":
        return "GK"
    if position == "CB":
        return "CB"
    if position in {"RB", "LB", "RWB", "LWB"}:
        return "FB"
    if position == "CDM":
        return "CDM"
    if position == "CM":
        return "CM"
    if position == "CAM":
        return "CAM"
    if position in {"RM", "LM", "RW", "LW"}:
        return "Winger"
    if position == "ST":
        return "ST"
    return ""


def normalize_role(value: str, position: str) -> str:
    text = normalize_text(value or "").replace("`", "").strip()
    role_map = {
        "gk": "GK",
        "cb": "CB",
        "fb": "FB",
        "fullback": "FB",
        "full back": "FB",
        "cdm": "CDM",
        "dm": "CDM",
        "cm": "CM",
        "cam": "CAM",
        "am": "CAM",
        "winger": "Winger",
        "wide": "Winger",
        "st": "ST",
        "striker": "ST",
    }
    role = role_map.get(text.lower())
    if role in VALID_ROLE_BUCKETS:
        return role
    return role_from_position(position)


def is_autogenerated_player_name(name: str) -> bool:
    return bool(AUTOGENERATED_NAME_RE.search(name or ""))


def camel_record(row: dict, league_multipliers: dict[str, float]) -> dict | None:
    def get(*keys):
        for key in keys:
            if key in row and str(row[key]).strip() != "":
                return str(row[key]).strip()
        return ""

    club = get("club")
    league = get("league", "competition")
    country = get("country")
    name = get("player", "name")
    position = normalize_position(get("position", "pos"))

    if not club or not league or not name or not position:
        return None
    if is_autogenerated_player_name(name):
        return None
    if league not in SUPPORTED_LEAGUES:
        return None

    role_bucket = normalize_role(get("role_bucket", "roleBucket", "role"), position)
    if not role_bucket:
        return None

    league_multiplier = parse_number(
        get("league_multiplier", "leagueMultiplier"),
        league_multipliers.get(league, 1.0),
    )

    mode_type = "champions_league" if league == "Champions League" else "league"

    return {
        "id": f"{slugify(club)}-{slugify(name)}",
        "name": name,
        "club": club,
        "league": league,
        "country": country,
        "competition": league,
        "position": position,
        "roleBucket": role_bucket,
        "minutes": int(parse_number(get("minutes"), 0)),
        "goals": int(parse_number(get("goals"), 0)),
        "assists": int(parse_number(get("assists"), 0)),
        "cleanSheets": int(parse_number(get("clean_sheets", "cleanSheets"), 0)),
        "tacklesInterceptions": int(parse_number(get("tackles_interceptions", "tacklesInterceptions"), 0)),
        "keyPassesDribbles": int(parse_number(get("key_passes_dribbles", "keyPassesDribbles"), 0)),
        "shotsOnTarget": int(parse_number(get("shots_on_target", "shotsOnTarget"), 0)),
        "leagueMultiplier": float(league_multiplier),
        "iogSeed": float(parse_number(get("iog_seed_pre_norm", "iogSeed", "iog_seed"), 0)),
        "estimated": parse_bool(get("estimated"), True),
        "modeType": mode_type,
    }


def read_input_path(path: Path | None) -> Path:
    if path and path.exists():
        return path
    if DEFAULT_INPUT_PATH.exists():
        return DEFAULT_INPUT_PATH
    if ALT_INPUT_PATH.exists():
        return ALT_INPUT_PATH
    raise FileNotFoundError(
        f"Club mode input not found. Expected {DEFAULT_INPUT_PATH} or {ALT_INPUT_PATH}."
    )


def parse_league_multipliers(lines: list[str]) -> dict[str, float]:
    multipliers = {}
    section = ""
    for raw in lines:
        line = strip_inline_comment(raw)
        if not line:
            continue
        section_match = re.match(r"^\[(.+)]$", line)
        if section_match:
            section = section_match.group(1).strip()
            continue
        if section == "LEAGUE_MULTIPLIERS" and "=" in line:
            league, value = [part.strip() for part in line.split("=", 1)]
            if league in SUPPORTED_LEAGUES:
                multipliers[league] = float(parse_number(value, 1.0))
    return multipliers


def parse_csv_blocks(lines: list[str]) -> list[tuple[str, list[str]]]:
    blocks = []
    section = ""
    current = []

    for raw in lines:
        line = strip_inline_comment(raw)
        if not line:
            continue

        section_match = re.match(r"^\[(.+)]$", line)
        if section_match:
            if current:
                blocks.append((section, current))
                current = []
            section = section_match.group(1).strip()
            continue

        if section.startswith("/") or section in {"META", "MODE_RULES", "LEAGUE_MULTIPLIERS", "IOG_PSEUDOCODE", "SAMPLE_CLUBS", "END"}:
            continue

        if "," in line:
            current.append(line)

    if current:
        blocks.append((section, current))

    normalized = [block for block in blocks if block[0] == "PLAYER_ROWS_NORMALIZED_CSV"]
    return normalized or [block for block in blocks if block[0].startswith("PLAYER_")]


def parse_players(input_path: Path) -> list[dict]:
    lines = input_path.read_text(encoding="utf-8-sig", errors="replace").splitlines()
    league_multipliers = parse_league_multipliers(lines)
    rows_by_id = {}
    skipped = 0

    for _section, block_lines in parse_csv_blocks(lines):
        if not block_lines:
            continue
        reader = csv.DictReader(block_lines)
        if not reader.fieldnames:
            continue
        for row in reader:
            record = camel_record(row, league_multipliers)
            if not record:
                skipped += 1
                continue
            rows_by_id[record["id"]] = record

    players = sorted(rows_by_id.values(), key=lambda item: (item["league"], item["club"], item["name"]))
    if not players:
        raise RuntimeError(f"No valid club player rows found in {input_path}. Skipped rows: {skipped}")
    return players


def write_json(players: list[dict], output_path: Path, src_output_path: Path):
    for path in (output_path, src_output_path):
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as handle:
            json.dump(players, handle, indent=2, ensure_ascii=False)
            handle.write("\n")


def print_report(players: list[dict]):
    clubs = Counter(player["club"] for player in players)
    leagues = Counter(player["league"] for player in players)
    positions = Counter(player["position"] for player in players)
    roles = Counter(player["roleBucket"] for player in players)

    print("clubs imported")
    print(len(clubs))
    print("players imported")
    print(len(players))
    print("players per league")
    for league in sorted(leagues):
        print(f"{league}: {leagues[league]}")

    print("Total Clubs")
    print(len(clubs))
    print("Total Players")
    print(len(players))
    print("League Breakdown")
    for league, count in sorted(leagues.items()):
        print(f"  {league}: {count}")
    print("Position Breakdown")
    for position, count in sorted(positions.items()):
        print(f"  {position}: {count}")
    print("Role Breakdown")
    for role, count in sorted(roles.items()):
        print(f"  {role}: {count}")
    print("Club Mode Database Ready")


def import_club_mode(input_path: Path | None, output_path: Path, src_output_path: Path):
    resolved_input = read_input_path(input_path)
    print(f"Parsing club mode file: {resolved_input}")
    players = parse_players(resolved_input)
    write_json(players, output_path, src_output_path)
    print_report(players)
    print(f"wrote: {output_path}")
    print(f"wrote: {src_output_path}")
    return players


def main():
    parser = argparse.ArgumentParser(description="Import Galactico11 club mode pasted text into JSON")
    parser.add_argument("--input", type=Path, default=None, help="Path to club.txt")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH, help="Manual club JSON output")
    parser.add_argument("--src-output", type=Path, default=DEFAULT_SRC_OUTPUT_PATH, help="App club JSON output")
    args = parser.parse_args()

    import_club_mode(args.input, args.output, args.src_output)


if __name__ == "__main__":
    main()
